require([
	"dojo/dom",
	"dojo/request",
	"dojo/json",
	"dojo/_base/array",
	"dojo/domReady",
	"dojo/_base/declare",
	"dojo/parser",
	"dojo/ready",
	"dijit/_WidgetBase",
	"dojo/dom-construct",
	"dijit/_TemplatedMixin",
	"dojo/request",
	"dojo/promise/all",
	'demo/demo-layer',
	'PersonWidget/PersonWidget'
]);
