<a href="${pageContext.servletContext.contextPath}/">Home</a><br/>
<a href="${pageContext.servletContext.contextPath}/hello">Hello</a><br/>
<a href="${pageContext.servletContext.contextPath}/events">Events</a><br/>
<a href="${pageContext.servletContext.contextPath}/query">Query</a><br/>
<a href="${pageContext.servletContext.contextPath}/animations">Animations</a><br/>
<a href="${pageContext.servletContext.contextPath}/ajax">Ajax</a><br/>
<a href="${pageContext.servletContext.contextPath}/simple-module">Simple Module</a><br/>
<a href="${pageContext.servletContext.contextPath}/classes">Classes</a><br/>
<a href="${pageContext.servletContext.contextPath}/calculator">Calculator</a><br/>
<a href="${pageContext.servletContext.contextPath}/image-zoomer">Image Zoomer</a><br/>
<a href="${pageContext.servletContext.contextPath}/tables">Tables</a><br/>
<a href="${pageContext.servletContext.contextPath}/filtering-select">Filtering Select</a><br/>
<a href="${pageContext.servletContext.contextPath}/mobile">Mobile</a><br/>
